version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: build
cache:
  paths:
    - "./node_modules/**/*"
